From openjdk:8
copy ./target/ec2-masterclass-sample-app-0.0.1-SNAPSHOT.jar ec2-masterclass-sample-app-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "/ec2-masterclass-sample-app-0.0.1-SNAPSHOT.jar"]
EXPOSE 8765
