node {
        stage('Checkout') {
            git credentialsId: 'job1', url: 'https://github.com/Venkat07m/sample-java'
        }
        stage('Build') {
            def mvnHome = tool name: 'M2_HOME', type: 'maven'
            sh "${mvnHome}/bin/mvn package"
        }
}
