node {
        stage('Checkout') {
            git credentialsId: 'job1', url: 'https://github.com/Venkat07m/core-java.git'
        }
        stage('MVN Package'){
           def mvnHome = tool name: 'M2_HOME', type: 'maven'
           sh "${mvnHome}/bin/mvn package"
        }
}
